execute pathogen#infect()
execute pathogen#helptags()

filetype plugin indent on
syntax on

"Show line numbers
set nu
"Show what's pressed in command mode
set showcmd
"Expand tabs as 4 spaces
set expandtab
set shiftwidth=4
set tabstop=4

let mapleader = ';'

"highlight YAML frontmatter in jekyll
let g:vim_markdown_frontmatter = 1

"Python 3 syntax checking
let g:pymode_python = 'python3'

"disable pymode folding because it is painfully slow
let g:pymode_folding = 0

"close documentation preview window after autocomplete
augroup preview
    autocmd!
    autocmd CompleteDone * pclose
augroup END

"shortcut to lint a python file
nnoremap <leader>l :PymodeLintAuto<cr>

"open and edit vimrc
nnoremap <leader>ev :vsplit $MYVIMRC<cr>

"source vimrc to apply it in current session
nnoremap <leader>sv :source $MYVIMRC<cr>

"insert blank line below without leaving normal mode
nnoremap <C-o> o<Esc>k
