execute pathogen#infect()
execute pathogen#helptags()

filetype plugin indent on
syntax on

"Show line numbers
set nu
set showcmd

let mapleader = ';'

"Highlight YAML frontmatter in jekyll
let g:vim_markdown_frontmatter = 1

"Python 3 syntax checking
let g:pymode_python = 'python3'

"Don't compress two blank lines to one in python
let g:topiary_ft_allow_two_blank_lines = ['python']

"close documentation preview window after autocomplete
augroup preview
    autocmd!
    autocmd CompleteDone * pclose
augroup END

"open and edit vimrc
nnoremap <leader>ev :vsplit $MYVIMRC<cr>

"source vimrc to apply it in current session
nnoremap <leader>sv :source $MYVIMRC<cr>
